'use client';

import { useCallback, useState } from 'react';
import { useDropzone, FileRejection } from 'react-dropzone';
import { UploadCloud, FileArchive, Loader2 } from 'lucide-react';
import JSZip from 'jszip';
import { toast } from 'sonner';
import clsx from 'clsx';

interface SandboxLoaderProps {
    onLoad: (urls: string[]) => void;
}

export function SandboxLoader({ onLoad }: SandboxLoaderProps) {
    const [isExtracting, setIsExtracting] = useState(false);
    const [progress, setProgress] = useState(0);

    const processZip = async (file: File) => {
        setIsExtracting(true);
        setProgress(0);
        try {
            const zip = new JSZip();
            const contents = await zip.loadAsync(file);

            // Filter for supported image types and ignore macOS __MACOSX system folders
            const imageFiles = Object.keys(contents.files).filter((name) => {
                if (contents.files[name].dir) return false;
                if (name.includes('__MACOSX')) return false;
                const lowerName = name.toLowerCase();
                return lowerName.endsWith('.webp') || lowerName.endsWith('.png') || lowerName.endsWith('.jpg') || lowerName.endsWith('.jpeg');
            });

            if (imageFiles.length === 0) {
                throw new Error("No supported image files (.webp, .png, .jpg) found in the ZIP.");
            }

            // Ensure natural sorting (frame_001, frame_002, etc.)
            imageFiles.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

            const urls: string[] = [];
            let processed = 0;

            for (const filename of imageFiles) {
                const fileData = await contents.file(filename)!.async('blob');
                const url = URL.createObjectURL(fileData);
                urls.push(url);
                processed++;
                setProgress(Math.round((processed / imageFiles.length) * 100));
            }

            toast.success(`Loaded ${urls.length} frames successfully!`);
            onLoad(urls);

        } catch (error) {
            console.error(error);
            toast.error(error instanceof Error ? error.message : "Failed to extract ZIP file.");
        } finally {
            setIsExtracting(false);
            setProgress(0);
        }
    };

    const onDrop = useCallback(
        (acceptedFiles: File[], fileRejections: FileRejection[]) => {
            if (fileRejections.length > 0) {
                toast.error(fileRejections[0].errors[0].message);
                return;
            }

            if (acceptedFiles.length > 0) {
                processZip(acceptedFiles[0]);
            }
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        []
    );

    const { getRootProps, getInputProps, isDragActive } = useDropzone({
        onDrop,
        accept: {
            'application/zip': ['.zip'],
            'application/x-zip-compressed': ['.zip'],
        },
        maxFiles: 1,
        disabled: isExtracting,
    });

    return (
        <div className="w-full max-w-2xl mx-auto space-y-6 animate-slide-up">
            <div className="text-center space-y-2">
                <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-brand-500/10 mb-4">
                    <FileArchive className="w-6 h-6 text-brand-400" />
                </div>
                <h2 className="text-2xl font-bold text-white">Load Image Sequence</h2>
                <p className="text-[var(--text-muted)]">
                    Drop the ZIP file generated by the Asset Optimizer here to preview the scroll animation.
                </p>
            </div>

            <div
                {...getRootProps()}
                className={clsx(
                    'group relative w-full rounded-2xl border-2 border-dashed transition-all duration-300 ease-in-out cursor-pointer p-12 text-center',
                    isDragActive
                        ? 'border-brand-500 bg-brand-500/5 rotate-1 scale-[1.02]'
                        : 'border-[var(--border)] hover:border-[var(--border-hover)] bg-white/[0.02] hover:bg-white/[0.05]',
                    isExtracting && 'opacity-50 cursor-wait pointer-events-none'
                )}
            >
                <input {...getInputProps()} />

                <div className="flex flex-col items-center justify-center gap-4">
                    {isExtracting ? (
                        <>
                            <Loader2 className="w-10 h-10 text-brand-400 animate-spin" />
                            <div>
                                <p className="text-sm font-medium text-[var(--text-primary)]">
                                    Extracting Frames...
                                </p>
                                <p className="text-xs text-[var(--text-muted)] mt-1">{progress}% Complete</p>
                            </div>
                        </>
                    ) : (
                        <>
                            <div className="p-4 rounded-xl bg-white/5 group-hover:bg-brand-500/10 group-hover:text-brand-400 transition-colors">
                                <UploadCloud className="w-8 h-8" />
                            </div>
                            <div>
                                <p className="text-sm font-medium text-[var(--text-primary)]">
                                    Drag & drop your .zip file
                                </p>
                                <p className="text-xs text-[var(--text-muted)] mt-1">
                                    or click to browse local files
                                </p>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}
